### ISSUE TITLE
Got an error when equesting textDocument/codeAction

### ISSUE THREAD

**Issue by DouyuShinyruo** [cucumber/language-service#100]
### 👓 What did you see?
Got an error when equesting textDocument/codeAction.
I wrote `And 60 minutes have passed`  in my feature file and wrote `    @When("{int} {time_unit} have/has passed")` in my *.steps.java and I hope the feature file should jump to the step definition, but it got a error.
```
[Info  - 10:43:53 AM] * Found 37 parameter types in those glue files
[Info  - 10:43:53 AM]   * {time_unit} = (?i)(nanosecond|microsecond|millisecond|second|minute|hour|day)s?
```

### ✅ What did you expect to see?
The feature file should jump to the step definition.

### 📦 Which tool/library version are you using?
Cucumber for Visual Studio Code V1.3.0

**Comment by aslakhellesoy** [comment]
I think the best we can do here is to strip away any `(?i)` flags from parameter type regexps. This means they would no longer be case-insensitive in the language server (and the VSCode extension), so some Gherkin steps might show up as undefined.

Using the case insensitive flag in parameter type regexps is disallowed in the Ruby and JavaScript implementations of Cucumber Expressions:

https://github.com/cucumber/cucumber-expressions/blob/abc7d23299acc5d80de1ebd8fda94ab39015de3c/javascript/test/ParameterTypeTest.ts#L7-L12

https://github.com/cucumber/cucumber-expressions/blob/abc7d23299acc5d80de1ebd8fda94ab39015de3c/ruby/spec/cucumber/cucumber_expressions/parameter_type_spec.rb#L6-L12

The reason for this is that the `//i` flag is global. 

We don't have this limitation in the Java implementation of Cucumber Expressions. Do you think we should add a similar constraint there @mpkorstanje @mattwynne?

**Comment by mpkorstanje** [comment]
This is a difficult one.

It would definitely solve the problem for VS code, but also:

* It would be a breaking change so we'd have to delay it until Cucumber JVM 8.0.
* It's kinda useful. While most people will write `seconds`, a few might write `Seconds`. 
* It feels like playing whack-a-mole. What's the next cross platform difference that we could hit?

How does VS code currently handle Java regexes? 

Do we have JS libraries that support some of Javas Regex features that we could use?

Could we do a "best effort" and only strip the case insensitive pattern in VS code?

**Comment by aslakhellesoy** [comment]
> It's kinda useful

I agree. We'd have supported it in the JavaScript/Ruby implementations if `(?i)` was supported.

> How does VS code currently handle Java regexes? I would be surprised if we are the first.

We parse them and hope for the best. We have done 0 work to make sure they work.

We do some sanitisation of Python regexps - they also have some features that are unsupported in JavaScript. See https://github.com/cucumber/language-service/blob/e6579c2ed0faff4c286e6ebc40de05e2e5c6fb24/src/language/pythonLanguage.ts#L12-L26
Maybe we could have used https://github.com/jmchilton/pyre-to-regexp here.

> Do we have JS libraries that support some of Javas Regex features that we could use?

I found this:
* https://stackoverflow.com/questions/22828644/convert-java-regex-to-javascript-regex
* https://github.com/daiyam/node-regexp

I think the simplest solution for now is to just strip away any `(?i)`.

**Comment by leibson** [comment]
I see that this is closed, but I have a similar problem, but I am using C#, which should allow this.

`
Failed to reindex: Invalid regular expression: /(?i)Check in db the Tbl_Cards:/: Invalid group
`
Should I create a new ticket?

**Comment by kieran-ryan** [comment]
Thanks for catching @leibson - yes a new ticket would be great! 🙌
