### ISSUE TITLE
Error using in LunarVim

### ISSUE THREAD

**Issue by petrenkorf** [cucumber/language-service#190]
### 👓 What did you see?

Once I cloned the application to my computer and configured Lunar vim to use the correct executable, after opening a .feature file in LunarVim, the LSP log contains the following error:

`[START][2024-03-15 17:43:58] LSP logging initiated
[ERROR][2024-03-15 17:43:58] .../vim/lsp/rpc.lua:734    "rpc"   "/home/petris/Code/language-server/bin/cucumber-language-server.cjs"    "stderr"        "Error: Cannot find module '../dist/cjs/src/wasm/startStandaloneServer'\nRequire stack:\n- /home/petris/Code/language-server/bin/cucumber-language-server.cjs\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:990:27)\n    at Module.require (node:internal/modules/cjs/loader:1237:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (/home/petris/Code/language-server/bin/cucumber-language-server.cjs:4:35)\n    at Module._compile (node:internal/modules/cjs/loader:1378:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1437:10)\n    at Module.load (node:internal/modules/cjs/loader:1212:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1028:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)\n"`

And the application does works correctly.

### ✅ What did you expect to see?

The language server should be working succesfully, at least displaying messages such "Undefined Steps"

### 📦 Which tool/library version are you using?

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
npm 10.2.4
node v21.6.0

### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment]
@binhtran432k, have you observed this behaviour by any chance?

**Comment by binhtran432k** [comment]
> @binhtran432k, have you observed this behaviour by any chance?

@kieran-ryan, Thanks for bringing this to my attention. It seems this issue belongs in the `@cucumber/language-server` repository instead.

For your reference, @petrenkorf, we recently released a new version of @cucumber/language-server (v1.5.0): link to release: https://github.com/cucumber/language-server/releases/tag/v1.5.0. We recommend trying again with the latest version and raising the issue there if it persists. Thanks for your understanding!
