### ISSUE TITLE
C# Generate Step Definition is not quite correct

### ISSUE THREAD

**Issue by Issafalcon** [cucumber/language-service#52]
### 👓 What did you see?
Firstly, I'm loving the new features! Now I don't have to open Visual Studio to get that nice Gherkin writing experience!

I've been trying out the 'Generate Step Definition' feature for C#, and it works nicely in nvim to generate the code action, and puts the step definition in the right place. However, it doesn't quite produce valid Specflow compatible step definition.

For example say I create the following in my .feature file:
```
Given I do something
And I want to do it with 'Neovim'
```

If I pull up the code actions on the 'And' step and generate the step definition, it gives me:

```
[And("I want to do it with {string}")]
public void iWantToDoItWithString(string s)
{
}
```

There are a few things wrong with this that cause compile time errors
1. The 'And' attribute is not valid in Specflow. The 'And' attribute should instead be replaced by the relevant 'parent' step. In this case, it follows a 'Given' so the attribute would be 'Given'
2. The string parameter of the attribute needs to be a raw string and include regex for the string parameters instead of '{string}'.
3. The name of the method needs to be prefixed with the step definition attribute (i.e. 'Given')
4. By convention, specflow generated definitions don't replace placeholders with 'String' in the method name, but this doesn't seem to matter too much in order to link the step definition with the feature file

### ✅ What did you expect to see?

Given the points above, the step definition should look like this:
```
[Given(@"I want to do it with '([^']*)'")]
public void GivenIWantToDoItWith(string s)
{
}
```

### 📦 Which tool/library version are you using?

Nuget packages used:
```
    <PackageReference Include="SpecFlow" Version="3.9.*" />
    <PackageReference Include="SpecFlow.XUnit" Version="3.9.*" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.*" />
```

Using Nvim 0.7 with the cucumber_language_server v0.12.3

### 🔬 How could we reproduce it?

1. Create a new xUnit (or NUnit / MSTEst) .NET Core project with the above specflow packages
2. Create a .feature file using standard gherkin syntax
3. Modify the cucumber LSP settings to point to the appropriate folders. My neovim lsp settings for cucumber looks like this for example:
```
local opts = {
  settings = {
    cucumber = {
      features = { "**/*.feature" },
      glue = { "**/Steps/*.cs" },
    },
  },
}
```
4. Using whichever LSP client you like, hover over a step definition (an 'And' step) and run the code actions LSP request to be given the option to generate the step definition.
5. See the diagnostic errors produced by omnisharp LSP (or csharp_ls) or the compile time errors on building the project

### 📚 Any additional context?

My use case in a real scenario using Neovim
![image](https://user-images.githubusercontent.com/19861614/170223974-4355210d-4c0d-48db-9142-cc035def891e.png)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by aslakhellesoy** [comment]
> Firstly, I'm loving the new features! Now I don't have to open Visual Studio to get that nice Gherkin writing experience!

Thank you! ❤️ 

> The 'And' attribute is not valid in Specflow. The 'And' attribute should instead be replaced by the relevant 'parent' step. In this case, it follows a 'Given' so the attribute would be 'Given'

Thanks, I'm aware of this. It's the same for other language too. I've created https://github.com/cucumber/language-service/issues/53 to track this.

> The string parameter of the attribute needs to be a raw string and include regex for the string parameters instead of '{string}'.

We rely on the [Cucumber Expressions](https://github.com/cucumber/cucumber-expressions#cucumber-expressions) library to generate expressions for undefined steps. The library is currently only able to generate Cucumber Expressions, and not Regular Expressions.

You can add [CucumberExpressions.SpecFlow](https://github.com/gasparnagy/CucumberExpressions.SpecFlow) to get Cucumber Expressions support. @gasparnagy has said it might be added natively to SpecFlow in a future release.

> The name of the method needs to be prefixed with the step definition attribute (i.e. 'Given')

Happy to change that. Out of curiosity - is this a strict requirement, or just a SpecFlow convention? (It's not conventional in e.g. Cucumber-JVM to include the keyword in the method name since it's already on the annotation).

> By convention, specflow generated definitions don't replace placeholders with 'String' in the method name, but this doesn't seem to matter too much in order to link the step definition with the feature file

So to be clear, what you'd want is this?

```csharp
[And("I want to do it with {string}")]
public void GivenIWantToDoItWith(string s)
{
}
```

Is the convention similar for other parameters? e.g.

```csharp
[And("I have {int} tickets for {flight}")]
public void GivenIHaveTicketsFor(int i, flight Flight)
{
}
```

**Comment by Issafalcon** [comment]
Thanks for the reply @aslakhellesoy . 

When I have a bit more time I'll dive a bit deeper into the requirements of the specflow method names and how it works with the language service so I can give you a more detailed answer, and I will try with the cucumber expressions package to get more information about using with that also.

**Comment by Issafalcon** [comment]
Hi @aslakhellesoy - Just to clarify on a couple of points:

- The method naming on StepDefinition generation is a Specflow convention thing. It's just what I was used to from using the Visual Studio specflow extension when generating the definitions. You're right in that it doesn't matter what the method name is, but I guess it would be good to keep that consistency between generating from the LSP and from the VS extension
- The step definitions work when adding the CucumberExpressions.Specflow package to the project, so that's all good. The only thing missing is getting the LSP to link the definitions from the Gherkin correctly. I believe they are linking properly (LSP still thinks they are undefined) because when I helped to add support for c_sharp, I wasn't aware of the extensions package for expressions, and so the language service still won't link to those definitions.
