### ISSUE TITLE
Tags are not supported(yet?)

### ISSUE THREAD

**Issue by MetaMmodern** [cucumber/language-service#6]
Hello, I see that tag colorization support is included in Readme for this repo. But the Live demo of this repo: https://github.com/cucumber/monaco
does not show tags highlighting.
Is it something dependent on theme or do I need to enable it somehow in the editor config?

**Comment by aslakhellesoy** [comment]
Indeed - I forgot to add support for tags! I'm working on a fix...

**Comment by aslakhellesoy** [comment]
Correction: I actually had added support for tags:

* https://github.com/cucumber/language-service/blob/a9d4695a1b4cd87041617ef9b7b3420dd3d4950c/src/service/getGherkinSemanticTokens.ts#L68-L70
* https://github.com/cucumber/language-service/blob/a9d4695a1b4cd87041617ef9b7b3420dd3d4950c/test/service/getGherkinSemanticTokens.test.ts#L10
* https://github.com/cucumber/language-service/blob/a9d4695a1b4cd87041617ef9b7b3420dd3d4950c/test/service/getGherkinSemanticTokens.test.ts#L42-L46

If tags don't show in the editor it might be a styling issue. I'm also not sure whether `SemanticTokenTypes.class` is the appropriate token type to use for "tags". I'm a bit surprised there isn't a type for that in [the spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_semanticTokens).

I'll have a look at what token other language servers use for tags...

**Comment by MetaMmodern** [comment]
> Correction: I actually had added support for tags:
> 
> * https://github.com/cucumber/language-service/blob/a9d4695a1b4cd87041617ef9b7b3420dd3d4950c/src/service/getGherkinSemanticTokens.ts#L68-L70
> * https://github.com/cucumber/language-service/blob/a9d4695a1b4cd87041617ef9b7b3420dd3d4950c/test/service/getGherkinSemanticTokens.test.ts#L10
> * https://github.com/cucumber/language-service/blob/a9d4695a1b4cd87041617ef9b7b3420dd3d4950c/test/service/getGherkinSemanticTokens.test.ts#L42-L46
> 
> If tags don't show in the editor it might be a styling issue. I'm also not sure whether `SemanticTokenTypes.class` is the appropriate token type to use for "tags". I'm a bit surprised there isn't a type for that in [the spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_semanticTokens).
> 
> I'll have a look at what token other language servers use for tags...

Wow, hello @aslakhellesoy ) Well, talking about styling I just checked the live demo (https://cucumber.github.io/monaco/) and tags are white there, I mean the same color as steps. If you could maybe update the demo or show in this comment chain how can I add full color support it would be greately appreciated! (I've never worked with language servers and editors before on this kind of level, but I've managed to launch editor in our project)

**Comment by aslakhellesoy** [comment]
I think this will be fixed by #12. I'll do a bit more testing in `@cucumber/monaco` and if it looks good I'll make a new release.

**Comment by aslakhellesoy** [comment]
I've released `@cucumber/monaco 0.8.0` and `@cucumber/language-service 0.10.1` - please let us know if you still have problems! (Feel free to shout out if it works too 😄)

**Comment by MetaMmodern** [comment]
@aslakhellesoy awesome, thank you) Will it work with vs-dark theme as well?

**Comment by aslakhellesoy** [comment]
Yes, `vs-dark` works too

**Comment by MetaMmodern** [comment]
@aslakhellesoy hey man, just checked in our project, works fine. Thanks again)
