### ISSUE TITLE
Autocomplete not working with RegExp step definitions

### ISSUE THREAD

**Issue by yipingw** [cucumber/language-service#60]
### 👓 What did you see?

Plugin cannot recognize feature file and autocomplete not working, keyword highlight not working as well.

### ✅ What did you expect to see?

Autocomplete should be working correctly and keyword like Feature, Given, When etc should be highlighted.

### 📦 Which tool/library version are you using?

Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000
Cucumber plugin version: v1.0.9

### 🔬 How could we reproduce it?

1. Install plugin with version 1.0.9
2. Create a feature and typing some steps.
3. No autocomplete or keyword highlight even setting feature file path or glue path.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/2724357/169780631-77a7284f-cb7f-4d75-8fa2-1ee8df16c12e.png">

**Comment by aslakhellesoy** [comment]
This should be fixed in extension `1.2.5`. If not, please reopen this issue. Thanks for providing all the info to help us fix this!
