### ISSUE TITLE
Non-verbatim C# expressions are not recognized

### ISSUE THREAD

**Issue by gasparnagy** [cucumber/language-service#62]
With Cucumber Expressions in SpecFlow, it is not needed to use verbatim string literals for the step def expressions. So instead of `[When(@"I do something")]`, you would write `[When("I do something")]` (note the missing `@`).

The current implementation only recognizes step definitions with verbatim string [here](https://github.com/cucumber/language-service/blob/main/src/language/csharpLanguage.ts#L16), therefore the ones with normal string are not recognized and therefore the related steps are reported as undefined.

**Comment by Issafalcon** [comment]
I also noticed this when playing around with the cucumber expressions syntax in Specflow. The fix should be straightforward.

**Comment by aslakhellesoy** [comment]
I can confirm that this will be fixed by #68. I've verified with a local build of the VSCode extension and opened up https://github.com/specsolutions/202200607-EuroSTAR-AutomationWithSpecFlow/tree/main/A5
