### ISSUE TITLE
SpecFlow step definitions with parametrized cucumber expressions are not recognized

### ISSUE THREAD

**Issue by gasparnagy** [cucumber/language-service#63]
I have simple step definitions, like:

```
[Then(@"there should be {int} pizzas listed")]
public void ThenThereShouldBePizzasListed(int expectedCount)
{
            ...
}
```

or 

```
[Then(@"the home page main message should be: {string}")]
public void ThenTheHomePageMainMessageShouldBe(string expectedMessage)
{
    ...
}
```

but the related steps are displayed as undefined. The ones without parameter work...

**Comment by Issafalcon** [comment]
This sounds like a perfectly sensible approach to me @aslakhellesoy . Not being as familiar as yourself with this codebase, it sounds like, from your description, that this will work across step definitions in all languages.

One thing to note is the `StepArgumentTransformation` will be a verbatim string literal when special regex characters are used (i.e. `@"regex characters (.*)"`). I'm not sure if that impacts the implementation.

**Comment by gasparnagy** [comment]
@aslakhellesoy Thx for the improvements. I have some notes/feedback.

- The unnamed parameters can be used with type name as you have observed, but makes sense to mention that this is always the .NET type name, not the c# keyword (`Int32` vs `int`). But the extension defines the most commonly used c# type keywords and use them as an alias for the full type name. So if you make a conversion with `decimal` return type, you will be able to use it both as `{Decimal}` (because this is the type name) or `{decimal}` because this is an alias for `{Decimal}`.
- Not with the plugin, but with the [final integration](https://github.com/SpecFlowOSS/SpecFlow/pull/2595), you will be able to make named parameter types in `[StepArgumentTransformation("some-regex", Name = "mytypename")]`.
- Again in the final version we had to introduce an automatic inclusion of enumeration parameter types. Enums can be converted by default by SpecFlow anyway, so you want to be able to use `{Color}` (assuming Color is an enum type), without having any StepArgumentTransformation for them. 
- Altogether the parameter matching is fairly complex, because it had to match with the existing parameter type system of SpecFlow, so in the VS extension we simply use `.*?` for all cucumber expression parameters. I haven't run into conflict so far and generally it is better to show a match that might cause parameter errors runtime than showing it as "unspecified" just because we could not interpret perfectly the parameter rules. I would like to keep highlighting, that many teams use assets (e.g. step argument conversions) from external assemblies, so by only parsing c# it is never going to be perfect. So it is better to prepare for imperfection. 
- In general verbatim and non-verbatim C# strings are interchangeable. So theoretically we should support both in all places where we need strings. Also with new C# you can use interpolated strings in attributes `$"hello {foo} bar"`, but this is fortunately very rarely used. And you can also use constants as well, but that is also rarely used.

**Comment by Issafalcon** [comment]
The comprehensiveness of @gasparnagy 's reply compared to mine does a good job of highlighting the difference of one who writes the software, and one who simply consumes it :joy:

I think I'll defer to @gasparnagy in this case!
