### ISSUE TITLE
Add support for Go (Godog)

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/language-service#72]
See [CONTRIBUTING.md](https://github.com/cucumber/language-service/blob/main/CONTRIBUTING.md) for detailed instructions about how to prepare a pull request for this.

**Comment by aslakhellesoy** [comment]
@dumpsterfireproject @vearutop @mxygem @mattwynne you might be interested in following this issue so the [Cucumber VSCode Extension](https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official) will work with Godog!

**Comment by vearutop** [comment]
Interesting, if we could fix "undefined-step" for `godog` this extension would become very very helpful (and maybe could work as an implementation strategy for https://youtrack.jetbrains.com/issue/GO-5655).

Could you share some docs or places in code that are responsible for steps detection and parsing?

**Comment by aslakhellesoy** [comment]
> Could you share some docs or places in code that are responsible for steps detection and parsing?

@vearutop see [CONTRIBUTING.md](https://github.com/cucumber/language-service/blob/main/CONTRIBUTING.md#add-support-for-a-new-programming-language) for details.

**Comment by mirogta** [comment]
@aslakhellesoy not a big fan of godog… if I wanted to add a support for Go but [go-bdd](https://github.com/go-bdd/gobdd), would that go under this same issue or a different one?

**Comment by mirogta** [comment]
@aslakhellesoy Draft [PR](https://github.com/cucumber/language-service/pull/130) created. I'd appreciate some help with testing it. It seems to be all too simple.
