### ISSUE TITLE
Add pytest-bdd plugin's support

### ISSUE THREAD

**Issue by sevapopov2** [cucumber/language-service#80]
### 🤔 What's the problem you're trying to solve?
I am trying to use automatic steps definition with Cucumber's extension with pytest as a framework for tests and pytestt-bdd plugin for BDD testing. When trying to invoke code actions in the feature file now, there is the message that no code actions are available to use. Also, auto completion isn't supported when pytest-bdd is used and there are reports that steps aren't defined. However, all indentations are written correctly.

### ✨ What's your proposed solution?
A support for pytest-bdd to be able to create step definitions automatically from feature files created earlier using code actions panel. The support for autocompletion when pytest-bdd is used.

### ⛏ Have you considered any alternatives or workarounds?
No. Unfortunately I haven't found any methods to be able to use this extension in conjunction with pytest and it's plugin for BDD tests.

**Comment by aslakhellesoy** [comment]
Implementing this is not a priority for me.

If anybody else wants to add support for pytest-bdd, you can modify the existing Python support (which currently supports behave). It should only be a matter of adding more tree-sitter queries to discover step definitons using the [pytest-bdd/](https://pypi.org/project/pytest-bdd/) syntax.

See [CONTRIBUTING.md](https://github.com/cucumber/language-service/blob/main/CONTRIBUTING.md#add-support-for-a-new-programming-language) for more details.

**Comment by aslakhellesoy** [comment]
@sevapopov2 is this something you'd be able to contribute yourself?

**Comment by sevapopov2** [comment]
I haven't done such job before, but I am trying to understand how to do that. I am installing all packages mentioned in vscode/CONTRIBUTING.md file and getting permition error messages while completing npm link command.
Do I understand correctly that I need to complete the steps mentioned in "Adding a new programming language" section in language-service/CONTRIBUTING.md file? Thank you!

**Comment by sevapopov2** [comment]
Before trying to implement pytest-bdd to this extension I decided to see how it works with behave.
I created a feature file, created empty steps file and a other empty file but when I am pressing ctrl+. in the feature file it doesn't suggest me to create step definition file, also it writes that steps aren't defined, though I formated them with CTRL+Shift+i command.
Can it be an issue that I am using VSCode version on Arch Linux with this extension?
Each time I write steps there are warnings that they aren't defined even when using a test environment with behave installed.
Thank you!

**Comment by aslakhellesoy** [comment]
Moved to https://github.com/cucumber/language-service/pull/84
