### ISSUE TITLE
Support for tsx step definitions

### ISSUE THREAD

**Issue by kblestarge** [cucumber/language-service#87]
### 🤔 What's the problem you're trying to solve?

I'm trying to use this extension with a React app, but no matter how I configure the settings.json -> cucumber.glue settings I can't seem to get it to work with my step definitions defined in .tsx files.

Here's what I'm seeing:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/11730298/187250652-da3f9a1f-3c63-4730-b236-c68096b312a7.png">

### ✨ What's your proposed solution?

Add support for this, ideally out of the box with the default cucumber.glue config.

### ⛏ Have you considered any alternatives or workarounds?

Nope. Got any suggestions?

### 📚 Any additional context?

settings.json:
```
{
    "editor.tabSize": 2,
    "window.zoomLevel": 1,
    "bracketPairColorizer.depreciation-notice": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "cucumber.glue": [
        "cypress/integration/**/*.tsx",
        "cypress/integration/**/*.ts",
        "src/test/**/*.java",
        "features/**/*.php",
        "features/**/*.py",
        "tests/**/*.py",
        "features/**/*.rb",
        "*specs*/**/.cs"
    ]
}
```

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by aslakhellesoy** [comment]
I think we're going to need a fix for this. The language service only parses TypeScript, not TSX. See https://github.com/tree-sitter/tree-sitter-typescript.

It should be possible to add though. See [CONTRIBUTING](https://github.com/cucumber/language-service/blob/main/CONTRIBUTING.md#add-support-for-a-new-programming-language).

Would you be interested in helping out with a pull request @kblestarge?

**Comment by kblestarge** [comment]
@aslakhellesoy I might be interested. I'm not sure I have time tho. Let me see what my weekend looks like and get back to you.

**Comment by kblestarge** [comment]
@aslakhellesoy would you suggest adding a new language called `tsx`? or have .tsx files recognized under the Typescript language?
(looking for tips in case I choose to contribute on this)

**Comment by aslakhellesoy** [comment]
I’d definitely recommend adding a new language. There might be some duplication with `ts`, but I wouldn’t worry about that. We can always refactor and remove duplication later.

Thanks for helping out! ❤️

**Comment by aslakhellesoy** [comment]
I figured out a way to do this by simply switching from `typescript` to `tsx` - even for plain old TypeScript without JSX!
