### ISSUE TITLE
And step not being recognised as a step in feature file

### ISSUE THREAD

**Issue by bgibb95** [cucumber/language-service#88]
### 👓 What did you see?

**And** step not being recognised as a step in feature file.

### ✅ What did you expect to see?

**And** steps found in TypeScript file and no warning messages.

### 📦 Which tool/library version are you using?

Cucumber VS Code extension - `v1.2.11`
VS Code - `v1.70.2 `
macOS Monterey - `v12.5.1 (21G83)`

```
 "devDependencies": {
    "@cypress/browserify-preprocessor": "^3.0.1",
    "@cypress/code-coverage": "^3.10.0",
    "@cypress/webpack-preprocessor": "^5.5.0",
    "@types/node": "^15.3.0",
    "cypress": "^8.6.0",
    "cypress-cucumber-preprocessor": "^4.2.0",
    "cypress-file-upload": "^5.0.8",
    "cypress-iframe": "^1.0.1",
    "typescript": "^4.1.3"
  }
```

### 🔬 How could we reproduce it?

**testing/e2e/cypress/integration/change-password.feature**

![Screenshot 2022-08-31 at 2 49 12 PM](https://user-images.githubusercontent.com/25341501/187682275-0e38fcb1-a764-4ce4-ba66-27c0ae9694d5.png)

**testing/e2e/cypress/integration/change-password/change-password.ts**

![Screenshot 2022-08-31 at 2 49 47 PM](https://user-images.githubusercontent.com/25341501/187682254-12da77f0-4197-42e0-bc4f-74b1d7e37660.png)

### 📚 Any additional context?

`settings.json:`
```
"cucumber.glue": ["**/e2e/cypress/integration/**/*.ts"],
"cucumber.features": ["**/e2e/cypress/integration/**/*.feature"]
```

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by bgibb95** [comment]
Thanks for the response and explanation. I had a look at the Cucumber documentation and it seems that Cucumber does recognise `And` and `But` keywords, and also mentions them as a solution to an anti-pattern.

[Cucumber Conjunction Steps](https://cucumber.io/docs/guides/anti-patterns/?sbsearch=And+step&lang=javascript#conjunction-steps
)
<img width="1417" alt="Screenshot 2022-09-02 at 9 33 30 AM" src="https://user-images.githubusercontent.com/25341501/188085200-94e8b9c9-2622-4b19-baba-38f43a38a6e5.png">

It seems that there could be value in adding support for `And` and `But` in step definitions, but I understand if we prefer not to.

**Comment by aslakhellesoy** [comment]
I'm closing this as I am convinced the fix should be in `cypress-cucumber-preprocessor` (removing these keywords from the step definition API)
