### ISSUE TITLE
No steps found, so all steps seem to be undefined, on macOS

### ISSUE THREAD

**Issue by BrianHawley** [cucumber/language-service#91]
### 👓 What did you see?

In feature files in my project, all steps get flagged as undefined steps.

### ✅ What did you expect to see?

Expected the steps to be defined, and be able to go to the definitions of those steps.

### 📦 Which tool/library version are you using?

MacOS 12.4 (Monterey), Ruby platform, cucumber 7.1.0, cucumber-rails 2.5.1. My steps are defined in `"features/step_definitions/*.rb"`, but the default cucumber.glue setting should include that directory as part of its `"features/**/*.rb"` entry. I also tried setting the cucumber.glue setting explicitly, but that didn't help.

### 🔬 How could we reproduce it?

1. Install VS Code latest version (1.69.0 at time of writing), and the Cucumber extension (version 1.2.7 at time of writing).
2. Create any feature file in `"features/*.feature"` which references any existing step defined in `"features/step_definitions/*.rb"`.
3. Open the feature file in VS Code.
4. See "cucumber.undefined-step" errors for every step in the feature file. 

### 📚 Any additional context?

I don't know if this matters, but I also have the "Cucumber (Gherkin) Full Support" extension installed, though disabled. Uninstalling that extension doesn't help, as I have the same issues with only the Cucumber extension installed. The "Cucumber (Gherkin) Full Support" extension, when installed and enabled, is able to find the step definitions, after overriding its "cucumberautocomplete.steps" setting. The cucumber command line tool is able to find the steps too.

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by aslakhellesoy** [comment]
Allright - Cucumber for VSCode 1.3.0 is being published as I write this. RegExp flags should now be recongised. Thanks for the feedback @vitaminj and @BrianHawley.

Please open a new issue if you're stil having problems.

**Comment by shahnawazm786** [comment]
i have java project in vscode my steps are not being identified 
i have following entry in setting.js 
{
  "java.configuration.updateBuildConfiguration": "automatic",
  "java.project.sourcePaths": ["demo", "demo\\src\\main\\practice"],
  "java.project.referencedLibraries": [],
  "cucumber.features": ["src/test/resources/**/*.feature"],
  "cucumber.glue": ["src/test/java/**/*.java"],
  "cucumberautocomplete.steps": ["src/test/java/**/*.feature"],
  "cucumberautocomplete.syncfeatures": ["src/test/**/*.feature"]
}
my feature file is under the test/resources/features/login.feature
still steps showing undefined
