### ISSUE TITLE
Issue with And/But detection in TypeScript

### ISSUE THREAD

**Issue by flyboarder** [cucumber/language-service#94]
### 👓 What did you see?

`And`/`But` is not recognized in as Step Definition, getting undefined step errors.

### ✅ What did you expect to see?

`And`/`But` is a valid keyword and steps are detected.

### 📦 Which tool/library version are you using?

vs-code extension v1.3.0

### 🔬 How could we reproduce it?

Use feature files with 'And' keyword and typescript, with VS Code Extension installed.

### 📚 Any additional context?

n/a

**Comment by aslakhellesoy** [comment]
We won't fix this - see details in #95
