### ISSUE TITLE
Implement Document Symbols Request

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/language-service#98]
### 🤔 What's the problem you're trying to solve?

See the outline of a Gherkin Document in my editor

### ✨ What's your proposed solution?

Implement [Document Symbols Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol).

### ⛏ Have you considered any alternatives or workarounds?

Yes - implementing it directly in a VSCode Extension. This would limit usage to VSCode users - other editor users would not get the functionality. See https://github.com/cucumber/vscode/pull/111#pullrequestreview-1128758566

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by 10xtechie** [comment]
@aslakhellesoy ,
Which keywords (`Scenario`, `Rule`) of **Cucumber** should we provided by this new service?

**Comment by aslakhellesoy** [comment]
We should look for the following keywords: `Feature`, `Rule`, `Scenario`, `Examples`. We might also want to add `Given/When/Then/And` (steps), but let's omit that for now.

I think you should add a new `getGherkinDocumentSymbols(gherkinSource: string): readonly DocumentSymbol[]` function in `src/service/getGherkinDocumentSymbols.ts`.

I recommend you start by writing a failing test that:

* calls `getGherkinDocumentSymbols(gherkinSource)` with a simple Gherkin source
* verifies that the returned document symbols are what you expect.

Look at https://github.com/cucumber/language-service/blob/main/test/service/getGherkinDiagnostics.test.ts for inspiration.

You might be able to implement the function with the help of the `walkGherkinDocument` function. It's already used in some of the other `src/service/*.ts` functions.

**Comment by aslakhellesoy** [comment]
Hi @10xtechie - have you made any progress on this? I have an implementation of this that I haven't pushed - I wanted to give you a chance to complete yours first :-)

**Comment by 10xtechie** [comment]
@aslakhellesoy ,
I am sorry for this late reply as I was tied up. Thanks for awaiting my implementations. I have just pushed my initial changes. I am in two minds: should LSP return the array of Document Symbols with custom tree format or should it return Document Symbols using [Tree View API Basics](https://code.visualstudio.com/api/extension-guides/tree-view).
Please provide me with your feedback; also not sure why the current test is failing.
